language: python
# well its really octave, but that is not supported

matrix:
  include:
    - python: "2.7"
      env: SYMPY_VER=0.7.5 DOCTEST=no
    - python: "2.7"
      env: SYMPY_VER=0.7.6 DOCTEST=yes
    - python: "3.4"
      env: SYMPY_VER=0.7.6 DOCTEST=yes

install:
  - sudo apt-add-repository --yes ppa:octave/stable
  - sudo apt-get update
  - sudo apt-get install octave
  - "pip install sympy==$SYMPY_VER"
  - git clone --single-branch --branch fortravis https://github.com/cbm755/doctest-for-matlab

# all commands here must have exit code 0 for the build to be called "passing"
script:
  - octave --eval "a=42;disp(a);ver;pwd;exit(0)"
  - pushd src; make; popd
  - pushd inst
  - octave --eval "syms x; A = [x sin(x) x^3]; exit(0)"
  - octave --eval "r = octsympy_tests; exit(r)"
  - cat octsympy_tests.log
  - if [ "x$DOCTEST" = "xyes" ]; then
        octave --path ../doctest-for-matlab/inst --eval "r = octsympy_doctests; exit(r)";
    fi
  - popd

#after_script:
#  - echo ${TRAVIS_TEST_RESULT}
